#!/usr/bin/env python
import rospy
from visualization_msgs.msg import Marker, MarkerArray


def scn1_marker():
    marker = Marker()

    marker.header.frame_id = "panda_link0"
    marker.header.stamp = rospy.Time.now()

    # set shape, Arrow: 0; Cube: 1 ; Sphere: 2 ; Cylinder: 3
    marker.type = 1
    marker.id = 0

    # Set the scale of the marker
    marker.scale.x = 0.20
    marker.scale.y = 0.20
    marker.scale.z = 0.16

    # Set the color
    marker.color.r = 1.0
    marker.color.g = 1.0
    marker.color.b = 0.0
    marker.color.a = 1.0

    # Set the pose of the marker
    marker.pose.position.x = 0.4
    marker.pose.position.y = 0
    marker.pose.position.z = 0.09
    marker.pose.orientation.x = 0.0
    marker.pose.orientation.y = 0.0
    marker.pose.orientation.z = 0.0
    marker.pose.orientation.w = 1.0
    return marker


def scn1_start():
    marker = Marker()

    marker.header.frame_id = "panda_link0"
    marker.header.stamp = rospy.Time.now()

    # set shape, Arrow: 0; Cube: 1 ; Sphere: 2 ; Cylinder: 3
    marker.type = 2
    marker.id = 1

    # Set the scale of the marker
    marker.scale.x = 0.025
    marker.scale.y = 0.025
    marker.scale.z = 0.025

    # Set the color
    marker.color.r = 1.0
    marker.color.g = 0.7
    marker.color.b = 0.0
    marker.color.a = 1.0

    # Set the pose of the marker
    marker.pose.position.x = 0.4
    marker.pose.position.y = 0.19
    marker.pose.position.z = 0.15
    marker.pose.orientation.x = 0.0
    marker.pose.orientation.y = 0.0
    marker.pose.orientation.z = 0.0
    marker.pose.orientation.w = 1.0
    return marker


def scn1_goal():
    marker = Marker()

    marker.header.frame_id = "panda_link0"
    marker.header.stamp = rospy.Time.now()

    # set shape, Arrow: 0; Cube: 1 ; Sphere: 2 ; Cylinder: 3
    marker.type = 2
    marker.id = 2

    # Set the scale of the marker
    marker.scale.x = 0.025
    marker.scale.y = 0.025
    marker.scale.z = 0.025

    # Set the color
    marker.color.r = 0.0
    marker.color.g = 1.0
    marker.color.b = 0.0
    marker.color.a = 1.0

    # Set the pose of the marker
    marker.pose.position.x = 0.4
    marker.pose.position.y = -0.19
    marker.pose.position.z = 0.15
    marker.pose.orientation.x = 0.0
    marker.pose.orientation.y = 0.0
    marker.pose.orientation.z = 0.0
    marker.pose.orientation.w = 1.0
    return marker


if __name__ == '__main__':
    rospy.init_node('rviz_marker')

    marker_pub = rospy.Publisher("/visualization_marker_array", MarkerArray, queue_size=2)
    mark_array = MarkerArray()
    mark_array.markers.append(scn1_marker())
    mark_array.markers.append(scn1_start())
    mark_array.markers.append(scn1_goal())
    while not rospy.is_shutdown():
        marker_pub.publish(mark_array)
        rospy.rostime.wallsleep(1.0)
